# Generated by Django 5.0.1 on 2024-02-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('avgX', models.FloatField()),
                ('avgY', models.FloatField()),
                ('avgZ', models.FloatField()),
                ('transport', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Dissertation3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('avgX', models.FloatField()),
                ('avgY', models.FloatField()),
                ('avgZ', models.FloatField()),
                ('transport', models.CharField()),
            ],
        ),
    ]
