# Generated by Django 5.0.1 on 2024-02-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dissertation4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('avgX', models.FloatField()),
                ('avgY', models.FloatField()),
                ('avgZ', models.FloatField()),
                ('transport', models.CharField()),
            ],
        ),
    ]
