# Generated by Django 5.0.1 on 2024-02-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dissertation4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dissertation3',
        ),
    ]
