# Generated by Django 5.0.1 on 2024-02-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_dissertation3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dissertation',
            new_name='Dissertation2',
        ),
    ]
