# Generated by Django 5.0.1 on 2024-02-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_dissertation_dissertation2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dissertation2',
        ),
    ]
