# Generated by Django 5.0.1 on 2024-02-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_dissertation2'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation4',
            name='standardD',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
