# Generated by Django 5.0.1 on 2024-02-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_dissertation4_standardd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dissertation4',
            old_name='speed',
            new_name='avgSpeed',
        ),
    ]
