# Generated by Django 5.0.1 on 2024-02-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_speed_dissertation4_avgspeed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dissertation4',
            new_name='Dissertation',
        ),
    ]
