# Generated by Django 5.0.1 on 2024-02-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_dissertation4_dissertation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dissertation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgSpeed', models.FloatField()),
                ('standardD', models.FloatField()),
                ('avgX', models.FloatField()),
                ('avgY', models.FloatField()),
                ('avgZ', models.FloatField()),
                ('barometer', models.FloatField()),
                ('transport', models.CharField()),
                ('activityType', models.CharField()),
                ('transitionType', models.CharField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
