# Generated by Django 5.0.1 on 2024-02-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_dissertation2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dissertation',
        ),
    ]
