# Generated by Django 5.0.1 on 2024-02-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_delete_dissertation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dissertation2',
            new_name='Dissertation',
        ),
    ]
