# Generated by Django 5.0.1 on 2024-02-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_dissertation2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dissertation',
        ),
    ]
