# Generated by Django 5.0.1 on 2024-02-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_dissertation2_dissertation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='lat2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dissertation',
            name='long2',
            field=models.FloatField(default=0.0),
        ),
    ]
