# Generated by Django 5.0.1 on 2024-02-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_dissertation_prediction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
