# Generated by Django 5.0.1 on 2024-02-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_busesforeachstop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusesForEachStop',
        ),
    ]
