# Generated by Django 5.0.1 on 2024-02-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_delete_busesforeachstop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusesForEachStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.CharField(db_column='502533031')),
            ],
        ),
    ]
