# Generated by Django 5.0.1 on 2024-02-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_busesforeachstop_my_field2'),
    ]

    operations = [
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field10',
            field=models.CharField(db_column='502533034', default='2, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field11',
            field=models.CharField(db_column='502532558', default='2, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field12',
            field=models.CharField(db_column='502533035', default='2, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field13',
            field=models.CharField(db_column='502532557', default='2, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field14',
            field=models.CharField(db_column='502533036', default='2, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field15',
            field=models.CharField(db_column='502532556', default='2, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field16',
            field=models.CharField(db_column='502533042', default='2, 14, 30, N30, 33'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field17',
            field=models.CharField(db_column='2700413565', default='2, 14, 30, N30, 33'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field18',
            field=models.CharField(db_column='502533043', default='2, 14, 30, N30, 33'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field19',
            field=models.CharField(db_column='502533044', default='2, 14, 30, N30, 33'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field20',
            field=models.CharField(db_column='502532547', default='2, 14, 30, N30, 33'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field21',
            field=models.CharField(db_column='502533046', default='2, 14, 30, N30, 33'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field22',
            field=models.CharField(db_column='502532542', default='2, 14, 30, N30, 33'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field23',
            field=models.CharField(db_column='502533141', default='14'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field24',
            field=models.CharField(db_column='502532431', default='14'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field25',
            field=models.CharField(db_column='502532428', default='14'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field26',
            field=models.CharField(db_column='502533143', default='14'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field27',
            field=models.CharField(db_column='502533145', default='14'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field28',
            field=models.CharField(db_column='502532425', default='14'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field29',
            field=models.CharField(db_column='502533147', default='14'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field3',
            field=models.CharField(db_column='502533030', default='2, 12, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field30',
            field=models.CharField(db_column='502532419', default='14'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field31',
            field=models.CharField(db_column='502533150', default='14'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field32',
            field=models.CharField(db_column='502533125', default='2, 30, 33'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field33',
            field=models.CharField(db_column='502532450', default='2, 30, 33'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field34',
            field=models.CharField(db_column='502533126', default='2, 30, 33, 7, 29, 5, 8, 3, 37, 49, 31'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field35',
            field=models.CharField(db_column='502532447', default='47, 37, 7, 31'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field36',
            field=models.CharField(db_column='502532438', default='3, 5, 29, 30, 2, 49, 8, 33'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field37',
            field=models.CharField(db_column='502532436', default='7, 31, 37, 47'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field38',
            field=models.CharField(db_column='502532433', default='5, 29, 30, 49, 8, 2, 3, 33'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field39',
            field=models.CharField(db_column='502533138', default='5, 29, 30, 49, 8, 2, 3, 33, 7, 31, 37'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field4',
            field=models.CharField(db_column='502532563', default='2, 12, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field40',
            field=models.CharField(db_column='502532417', default='X31, 31, 37, 47, 7'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field41',
            field=models.CharField(db_column='502532413', default='8, 49, 3, 2, X29, 33, 30, 14, 5, 29'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field42',
            field=models.CharField(db_column='502533155', default='31, 30, 29, 5, 33, 14, 37, 3, 8, 49, 7'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field43',
            field=models.CharField(db_column='502533477', default='2'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field44',
            field=models.CharField(db_column='502532411', default='37, 7, 31'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field45',
            field=models.CharField(db_column='502532408', default='33, 30, 8, 3, 45, 29, 5, 49, 35, 14'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field46',
            field=models.CharField(db_column='502533158', default='35, 14, 5, 8, 49, 7, 45'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field47',
            field=models.CharField(db_column='502533161', default='29, 33, 30, 3, 37, 31'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field5',
            field=models.CharField(db_column='502532936', default='2, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field6',
            field=models.CharField(db_column='502532670', default='2, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field7',
            field=models.CharField(db_column='502533032', default='2, 14, 30, N30, 12'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field8',
            field=models.CharField(db_column='502532560', default='2, 14, 30, N30, 12'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field9',
            field=models.CharField(db_column='502532559', default='2, 14, 30, N30, 12'),
        ),
    ]
