# Generated by Django 5.0.1 on 2024-03-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_busesforeachstop_my_field10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field48',
            field=models.CharField(db_column='502532673', default='2, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field49',
            field=models.CharField(db_column='502532675', default='2, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field50',
            field=models.CharField(db_column='502532934', default='2, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field51',
            field=models.CharField(db_column='502532676', default='2, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field52',
            field=models.CharField(db_column='502532933', default='2, 14, 30, N30'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field53',
            field=models.CharField(db_column='502532685', default='2, 30, N30, 48, 21, 400'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field54',
            field=models.CharField(db_column='502532931', default='2, 30, N30, 48, 21, 400'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field55',
            field=models.CharField(db_column='502532687', default='2, 30, N30, 48, 21, 400'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field56',
            field=models.CharField(db_column='502532929', default='2, 30, N30, 48, 21, 400'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field57',
            field=models.CharField(db_column='502532689', default='2, 30, N30, 48, 21, 400'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field58',
            field=models.CharField(db_column='502532928', default='2, 30, N30, 48, 21, 400'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field59',
            field=models.CharField(db_column='502532695', default='2, 30, N30, 48, 21, 400'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field60',
            field=models.CharField(db_column='502532924', default='2, 30, N30, 48, 21, 400'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field61',
            field=models.CharField(db_column='502532696', default='2, 30, N30, 48, 21, 400'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field62',
            field=models.CharField(db_column='502532733', default='2, 21'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field63',
            field=models.CharField(db_column='502532900', default='2, 21'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field64',
            field=models.CharField(db_column='502532735', default='2, 21'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field65',
            field=models.CharField(db_column='318118937', default='2, 21'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field66',
            field=models.CharField(db_column='502532738', default='2, 21'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field67',
            field=models.CharField(db_column='502532894', default='2, 4, 49, 253'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field68',
            field=models.CharField(db_column='502532749', default='2, 4, 49, 253'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field69',
            field=models.CharField(db_column='502532892', default='2, 4, 49, 253'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field70',
            field=models.CharField(db_column='502532751', default='2, 4, 49, 253'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field71',
            field=models.CharField(db_column='502532891', default='2, 4, 49, 253, X5, X6, X7'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field72',
            field=models.CharField(db_column='502532752', default='2, 4, 49, 253, X5, X6, X7'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field73',
            field=models.CharField(db_column='502532890', default='2'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field74',
            field=models.CharField(db_column='502532889', default='5'),
        ),
    ]
