# Generated by Django 5.0.1 on 2024-03-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_busesforeachstop_my_field48_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field75',
            field=models.CharField(db_column='502533023', default='3, 7, 8, 29, 31, 37, 47, 47B, N31, N37, X62'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field76',
            field=models.CharField(db_column='502532570', default='3, 7, 8, 29, 31, 37, 47, 47B, N31, X62'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field77',
            field=models.CharField(db_column='502533067', default='3, 7, 8, 29, 31, 37, 47, 47B, N31, N37, X62, 49'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field78',
            field=models.CharField(db_column='502532499', default='3, 7, 8, 29, 31, 37, 47, 47B, N31, 49'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field79',
            field=models.CharField(db_column='502532496', default='3, 7, 8, 29, 31, 37, 47, 47B, N31, X62, 49'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field80',
            field=models.CharField(db_column='502533070', default='3, 7, 8, 29, 31, 37, 47, 47B, N31, X62, 49'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field81',
            field=models.CharField(db_column='502532492', default='3, 7, 8, 29, 31, 37, 47, 47B, N31, 49'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field82',
            field=models.CharField(db_column='502533073', default='3, 7, 8, 29, 31, 37, 47, 47B, N31, 49, N37'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field83',
            field=models.CharField(db_column='502533077', default='3, 7, 8, 29, 31, 37, 47, 47B, N31, 49, N37'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field84',
            field=models.CharField(db_column='502532489', default='3, 7, 8, 29, 31, 37, 47, 47B, N31, 49'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field85',
            field=models.CharField(db_column='502533083', default='3, 7, 8, 29, 31, 37, 47, 47B, N31, 49, N37'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field86',
            field=models.CharField(db_column='502532486', default='3, 7, 8, 29, 31, 37, 47, 47B, N31, 49, X62'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field87',
            field=models.CharField(db_column='502533086', default='3, 7, 8, 29, 31, 37, 47, 47B, N31, 49, X62'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field88',
            field=models.CharField(db_column='3043498691', default='3, 7, 8, 29, 31, 37, 47, 47B, N31, 49, X62. 5'),
        ),
    ]
