# Generated by Django 5.0.1 on 2024-03-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_busesforeachstop_my_field75_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field100',
            field=models.CharField(db_column='502533545', default='5'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field101',
            field=models.CharField(db_column='502532453', default='5'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field102',
            field=models.CharField(db_column='502533121', default='5, 24'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field103',
            field=models.CharField(db_column='502533119', default='5, 24'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field104',
            field=models.CharField(db_column='502532461', default='5, 24'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field105',
            field=models.CharField(db_column='502533116', default='5, 24'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field106',
            field=models.CharField(db_column='502532463', default='5'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field107',
            field=models.CharField(db_column='502533094', default='5'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field108',
            field=models.CharField(db_column='502532458', default='5'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field109',
            field=models.CharField(db_column='502533092', default='5'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field110',
            field=models.CharField(db_column='502532469', default='5'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field111',
            field=models.CharField(db_column='502533090', default='5'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field89',
            field=models.CharField(db_column='502531274', default='5, 11, 15, 16, 23, 36'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field90',
            field=models.CharField(db_column='2454750879', default='5, 11, 15, 16, 23, 36'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field91',
            field=models.CharField(db_column='502531277', default='5, 11, 15, 16, 23, 36'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field92',
            field=models.CharField(db_column='502533549', default='5, 11, 15, 16, 23, 36'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field93',
            field=models.CharField(db_column='502531287', default='5'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field94',
            field=models.CharField(db_column='1280143680', default='5'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field95',
            field=models.CharField(db_column='502531288', default='5'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field96',
            field=models.CharField(db_column='502533547', default='5'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field97',
            field=models.CharField(db_column='502531293', default='5'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field98',
            field=models.CharField(db_column='502533546', default='5'),
        ),
        migrations.AddField(
            model_name='busesforeachstop',
            name='my_field99',
            field=models.CharField(db_column='502531297', default='5'),
        ),
    ]
